Fix assignment of `carto.googleCloudStorageServiceAccountKey.secretName` to use checked variable.
`carto.googleCloudStorageServiceAccountKey.secretName` is assigned by first checking if a var is already set and then taking another variables value. This seems inconsistent with how the rest of the chart works.

example:

suppose you have a `customization.yaml` that looks like this.

```yaml
appSecrets:
  googleCloudStorageServiceAccountKey:
    existingSecret:
      name: "bar"
      key: "foo"

# deliberately commented out in the example, to ensure there is no values set. 
# cartoSecrets:
#   googleCloudStorageServiceAccountKey:
#     existingSecret:
#       name: "foo"
#       key: "bar"

```

When your run `helm template carto carto/carto -f customizations.yaml` you will get a error that describes the expected variable not being set.

```
Error: template: carto/templates/workspace-api/deployment.yaml:290:27: executing "carto/templates/workspace-api/deployment.yaml" at <include "carto.googleCloudStorageServiceAccountKey.secretName" .>: error calling include: template: carto/templates/_helpers.tpl:169:11: executing "carto.googleCloudStorageServiceAccountKey.secretName" at <.Values.cartoSecrets.googleCloudStorageServiceAccountKey.existingSecret.name>: nil pointer evaluating interface {}.existingSecret
helm.go:88: [debug] template: carto/templates/workspace-api/deployment.yaml:290:27: executing "carto/templates/workspace-api/deployment.yaml" at <include "carto.googleCloudStorageServiceAccountKey.secretName" .>: error calling include: template: carto/templates/_helpers.tpl:169:11: executing "carto.googleCloudStorageServiceAccountKey.secretName" at <.Values.cartoSecrets.googleCloudStorageServiceAccountKey.existingSecret.name>: nil pointer evaluating interface {}.existingSecret
```

I also updated the helper to use `.Values.appSecrets.googleCloudStorageServiceAccountKey.existingSecret.key` instead of `.Values.cartoSecrets.googleCloudStorageServiceAccountKey.existingSecret.key` so it is defined in only one place in the `customizations.yaml` file.